{{- if and .Values.configuration.prometheus.enabled .Values.configuration.prometheus.gcpMonitoring.enabled -}}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ include "graphqlmetrics.fullname" . }}
  labels:
    {{- include "graphqlmetrics.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "graphqlmetrics.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.configuration.prometheus.path }}
      interval: {{ .Values.configuration.prometheus.gcpMonitoring.interval }}
      timeout: {{ .Values.configuration.prometheus.gcpMonitoring.timeout }}
  filterRunning: false
{{- end }}
